### ISSUE TITLE
DOCTYPE doesn't take effect when enabling browserlink in a new asp.net core mvc app

### ISSUE THREAD

**Issue by ryanwu** [aspnet/Templates#602] opened 2016-06-12 03:20 UTC
I create an mvc application via asp.net core web application template, running it and view the page source, I found <!DOCTYPE html> is there, while using chrome debug tool(F12), <!DOCTYPE html> disappeared.  While when I browser it in IE, it works well.

**Comment by jodavis** [comment] 2016-06-16 19:05
This is being caused by Browser Link, which is generating a BOM in the file. Chrome is interpreting the BOM as text, and so it starts interpreting everything after that as <body> content. That includes the 

This will be fixed in the next release of the Web Tools. In the meantime, you can work around this issue by disabling app.UseBrowserLink() or using a browser other than Chrome.

**Closed as completed by jodavis** 2016-06-16 19:05 UTC
