### ISSUE TITLE
ReturnUrl is never set - always null

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Templates#420] opened 2016-03-01 22:40 UTC
This is documented in [on SO](https://stackoverflow.com/questions/827905/asp-net-mvc-login-returnurl-always-null/1206728#1206728)

To test: Create a new Web App with individual user accounts. Set a break point in Login. 
`public ActionResult Login(string returnUrl)`

returnUrl is never set and always null. The SO post has the fix (do the same thing with a Tag Helper on the new templates)

**Comment by Eilon** [comment] 2016-03-02 07:08
cc @Tratcher 

This sounds by design to me. The `returnUrl` is only populated automatically if you tried to access an authorized resource but were not authenticated or authorized. That's when the security middleware kicks in and redirects you to the login page with the `returnUrl`. If someone goes and clicks `Log in` on the site I don't see why you'd expect it to take you back to the original page. The user is on a different application flow at that time.

**Comment by rustd** [comment] 2016-03-03 19:27
Yep. returnUrl is set by the middleware. Closing as by design.

**Closed as completed by rustd** 2016-03-03 19:27 UTC
