### ISSUE TITLE
Web Application template should fallback to in-memory provider if SQL is not available

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Templates#558] opened 2016-05-10 18:08 UTC
Currently, the Web Application template fails if SQL is not available.  This will most likely happen on non-Windows platforms, but could also happen on Windows if SQL LocalDB is uninstalled.

I think the template should fallback to the in-memory provider if SQL is not available.

**Comment by peterblazejewicz** [comment] 2016-05-10 18:29
Somehow related is: https://github.com/aspnet/Templates/issues/422 discussing UI for templates option (correct configuration for new project can be crucial in context of this issue)

**Comment by rustd** [comment] 2016-05-10 18:45
The One ASP.NET UI is being redesigned for RTM to make this option more clear. Templates also represent real world apps so falling back to In-Memory won't be a good idea since in-memory is for testing.
Today, if you are creating ASP.NET apps on non-windows platforms, then you can use yeoman generators for ASP.NET.

**Comment by mikeharder** [comment] 2016-05-10 18:56
It appears my feedback is already included in #422.  I see a checkbox "enable for cross-platform development".  Feel free to resolve this as a dup of #422, unless you want to track it separately.

**Comment by rustd** [comment] 2016-05-10 23:11
Duplicate of #422

**Closed as completed by rustd** 2016-05-10 23:11 UTC
