### ISSUE TITLE
[Proposal]ASP.NET Core Static Website Template

### ISSUE THREAD

**Issue by sgjsakura** [aspnet/Templates#585] opened 2016-05-31 07:25 UTC
Hi all,
I want to build-up a static website (works with client site libraries like angularjs), however I'd like to take the advantage from Visual studio from bower package management, compiling scripts, publishing, etc. Could you please offer a new template for static websites? Many thanks!

**Comment by peterblazejewicz** [comment] 2016-05-31 18:48
duplicate of: #137 #541

**Comment by sayedihashimi** [comment] 2016-06-02 17:38
Our Visual Studio project system doesn't support "static" web projects yet really (website project does support this though). It will always run `dotnet` for projects today. We are making some changes and this is something that I would like to enable but we are not fully committed to this yet.

cc @BillHiebert

**Comment by Eilon** [comment] 2017-10-24 21:50
This issue was moved to aspnet/templating#113

**Closed as completed by Eilon** 2017-10-24 21:50 UTC
Labels: question
