### ISSUE TITLE
yo aspnet-generator console app bug.

### ISSUE THREAD

**Issue by yukozh** [aspnet/Templates#245] opened 2015-10-21 20:54 UTC
In commands value field, it still was ConsoleApplication, it is not the project name. So it cannot run correctly.

**Comment by yukozh** [comment] 2015-10-21 20:56
![image](https://cloud.githubusercontent.com/assets/2216750/10649903/2e83840a-7879-11e5-85f7-e6e6775dcb15.jpeg)

**Comment by yukozh** [comment] 2015-10-21 20:57
![image](https://cloud.githubusercontent.com/assets/2216750/10649953/5e9d80c8-7879-11e5-8fd3-e1b6742ecfe6.png)

**Comment by spboyer** [comment] 2015-10-21 23:33
@Kagamine please file this in http://github.com/omnisharp/generator-aspnet/issues
@peterblazejewicz

**Comment by yukozh** [comment] 2015-10-21 23:42
@spboyer Thanks, I created a PR to fix it.

**Comment by rustd** [comment] 2015-10-22 03:14
Closing this issue as this is not a bug in VS templates

**Closed as completed by rustd** 2015-10-22 03:14 UTC

**Comment by peterblazejewicz** [comment] 2015-10-22 19:06
@Kagamine 
Please use search, add your comments to that thread:
https://github.com/OmniSharp/generator-aspnet/issues/335
Tha'ts not generator issue
Thanks!
